version: '3.4'
services:
  web:
    build: 
      context: .
      target: build-env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '4001:4001'
    command: 'env PORT=4001 NODE_ENV=development HOST=0.0.0.0 yarn run dev'

volumes:
  node_modules: